# Generated by Django 3.1.1 on 2020-09-22 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_course_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(blank=True, default='static/img/teaching.jpg', null=True, upload_to=''),
        ),
    ]
