# Generated by Django 3.1.1 on 2020-11-13 13:21

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201113_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(blank=True, default='static/img/teaching.jpg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
