# Generated by Django 3.1.1 on 2020-11-13 13:27

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20201113_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='body',
            field=ckeditor.fields.RichTextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lesson',
            name='description',
            field=models.CharField(max_length=700),
        ),
    ]
